staging:
  maxRetry: 3
  deployment:
    timeout: 5m
    engine: helm3
    testRunner:
      timeout: 4m
      pollingTime: 5s
      testMock:
        result: true
    
activePromotion:
  tearDownDuration: 10s
  timeout: 10m
  maxHistories: 2
  deployment:
    timeout: 5m
    engine: helm3
    testRunner:
      timeout: 4m
      pollingTime: 5s
      testMock:
        result: true
  outdatedNotification:
    exceedDuration: 24h
    excludeWeekendCalculation: true

report:
  reportMock: true
  slack:
    channels:
      - samsahai
    componentUpgrade:
      interval: retry

components:
  - name: redis
    chart:
      repository: https://kubernetes-charts.storage.googleapis.com
      name: redis
    image:
      repository: bitnami/redis
      pattern: '5.*debian-9.*'
    source: public-registry
    values:
      image:
        repository: bitnami/redis
        pullPolicy: IfNotPresent
      cluster:
        enabled: false
      usePassword: false
      master:
        persistence:
          enabled: false
  - name: wordpress
    chart:
      repository: https://kubernetes-charts.storage.googleapis.com
      name: wordpress
    image:
      repository: bitnami/wordpress
      pattern: '5\.2.*debian-9.*'
    source: public-registry
    dependencies:
      - name: mariadb
        image:
          repository: bitnami/mariadb
          pattern: '10\.3.*debian-9.*'
        source: public-registry
    values:
      resources: null
      service:
        type: NodePort
      persistence:
        enabled: false
      mariadb:
        enabled: true
        replication:
          enabled: false
        master:
          persistence:
            enabled: false